"""Edge code tests. Owner: Person C.

Tests:
1. tiny_tree.c contains float thresholds from the sklearn-fitted tree
2. build_host.py exits 1 without gcc with the required message
"""
from __future__ import annotations

import re
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
C_DIR = REPO_ROOT / "skyguard" / "edge" / "c"
BUILD_HOST_PY = REPO_ROOT / "skyguard" / "edge" / "build_host.py"
PYTHON = sys.executable


def test_tiny_tree_c_contains_thresholds():
    """tiny_tree.c must contain at least one float threshold from the fitted tree.

    The file is generated by export.py (requires sklearn; blocked DLLs on this machine).
    We validate the committed file instead.
    """
    tiny_tree_c = C_DIR / "tiny_tree.c"
    assert tiny_tree_c.exists(), (
        f"tiny_tree.c not found at {tiny_tree_c}. Run: python skyguard/edge/export.py"
    )

    content = tiny_tree_c.read_text()

    # Must include the header
    assert "#include" in content, "tiny_tree.c must include tiny_tree.h"

    # Must define tree_predict
    assert "tree_predict" in content, "tiny_tree.c must define tree_predict"

    # Must contain at least one float threshold (e.g., <= 3.0409...f)
    threshold_pattern = re.compile(r"<=\s*-?\d+\.\d+f")
    matches = threshold_pattern.findall(content)
    assert len(matches) >= 1, (
        f"tiny_tree.c has no float thresholds from sklearn tree.\n"
        f"Content:\n{content}"
    )


def test_build_host_exits_1_without_gcc(tmp_path):
    """build_host.py must print 'gcc not found' and exit 1 when gcc is absent."""
    # Write a wrapper that monkeypatches shutil.which before importing build_host
    wrapper_code = textwrap.dedent(f"""\
        import sys, shutil

        _orig_which = shutil.which

        def _patched_which(cmd, **kw):
            if cmd == "gcc":
                return None
            return _orig_which(cmd, **kw)

        shutil.which = _patched_which

        import importlib.util
        from pathlib import Path

        bh_path = Path(r"{BUILD_HOST_PY}")
        spec = importlib.util.spec_from_file_location("build_host", str(bh_path))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        mod.main()
    """)

    wrapper = tmp_path / "run_no_gcc.py"
    wrapper.write_text(wrapper_code)

    result = subprocess.run(
        [PYTHON, str(wrapper)],
        capture_output=True, text=True, cwd=str(REPO_ROOT)
    )

    assert result.returncode == 1, (
        f"Expected exit code 1 when gcc missing, got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    combined = result.stdout + result.stderr
    assert "gcc not found" in combined, (
        f"Expected 'gcc not found' in output, got:\n{combined}"
    )


def test_tiny_tree_c_has_return_statements():
    """The committed tiny_tree.c must have return statements (decision nodes)."""
    tiny_tree_c = C_DIR / "tiny_tree.c"
    if not tiny_tree_c.exists():
        pytest.skip("tiny_tree.c not generated yet")
    content = tiny_tree_c.read_text()
    assert "return" in content, "tiny_tree.c must have return statements"
